name: 🚀 Angular Local Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 📦 Install Dependencies
        run: |
          cd ~/angular-app
          npm install

      - name: 🚀 Run Angular App with PM2
        run: |
          cd ~/angular-app
          npm install -g pm2
          pm2 delete angular-app || true
          pm2 start "npm start" --name "angular-app"
          pm2 save
